services:
  postgres:
    image: postgres:17-alpine
    container_name: geo-workstation-postgres
    environment:
      POSTGRES_DB: geo_workstation
      POSTGRES_USER: geo_workstation
      POSTGRES_PASSWORD: geo_workstation
    ports:
      - "5432:5432"
    volumes:
      - geo_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: geo-workstation-redis
    ports:
      - "6379:6379"
    volumes:
      - geo_redis_data:/data

volumes:
  geo_postgres_data:
  geo_redis_data:
